### ISSUE TITLE
Fresh install fails when restart

### ISSUE THREAD

**Issue by MmtBkn** [magento/magento2devbox-web#115]
Hi,

- I downloaded DevBox using this link with default config (CE/fresh install)
https://magento.com/tech-resources/downloads/magento/configure/
- Followed instructions
- Installed Docker version 17.03.1-ce, build c6d412e on my Windows 10 Enterprise,
- And completed setup. Yesterday everything was ok, however today, when I go to website, I realized that It doesn't work today. Nothing changed. Than I uninstalled, and re-installed everything again to verify that restart caused the problem.

When computer (probably docker too) restarts, I think it doesn't start database. I tried to run mysql start inside of container but I think mysql has separate container. I tried recompiling too. Here is what I get;
````
2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.store' doesn't exist, query was: SELECT `store`.* FROM `store` WHERE (`store`.`store_id`='1') ORDER BY `sort_order` ASC

Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.store' doesn't exist

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.store' doesn't exist, query was: SELECT `store`.* FROM `store` WHERE (`store`.`store_id`='1') ORDER BY `sort_order` ASC

#0 /var/www/magento2/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `store`....', Array)
#4 /var/www/magento2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(465): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `store`....', Array)
#5 /var/www/magento2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(520): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `store`....', Array)
#6 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(756): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 /var/www/magento2/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(342): Zend_Db_Adapter_Abstract->fetchRow(Object(Magento\Framework\DB\Select))
#8 /var/www/magento2/var/generation/Magento/Store/Model/ResourceModel/Store/Interceptor.php(102): Magento\Framework\Model\ResourceModel\Db\AbstractDb->load(Object(Magento\Store\Model\Store\Interceptor), '1', 'store_id')
#9 /var/www/magento2/vendor/magento/framework/Model/AbstractModel.php(531): Magento\Store\Model\ResourceModel\Store\Interceptor->load(Object(Magento\Store\Model\Store\Interceptor), '1', NULL)
#10 /var/www/magento2/vendor/magento/module-store/Model/Store.php(488): Magento\Framework\Model\AbstractModel->load('1', NULL)
#11 /var/www/magento2/var/generation/Magento/Store/Model/Store/Interceptor.php(24): Magento\Store\Model\Store->load('1', NULL)
#12 /var/www/magento2/vendor/magento/module-store/App/Config/Source/RuntimeConfigSource.php(181): Magento\Store\Model\Store\Interceptor->load('1')
#13 /var/www/magento2/vendor/magento/module-store/App/Config/Source/RuntimeConfigSource.php(112): Magento\Store\App\Config\Source\RuntimeConfigSource->getStoresData('1')
#14 /var/www/magento2/vendor/magento/framework/App/Config/ConfigSourceAggregated.php(40): Magento\Store\App\Config\Source\RuntimeConfigSource->get('stores/1')
#15 /var/www/magento2/var/generation/Magento/Framework/App/Config/ConfigSourceAggregated/Proxy.php(95): Magento\Framework\App\Config\ConfigSourceAggregated->get('stores/1')
#16 /var/www/magento2/vendor/magento/module-store/App/Config/Type/Scopes.php(50): Magento\Framework\App\Config\ConfigSourceAggregated\Proxy->get('stores/1')
#17 /var/www/magento2/vendor/magento/framework/App/Config.php(139): Magento\Store\App\Config\Type\Scopes->get('stores/1')
#18 /var/www/magento2/vendor/magento/module-store/Model/StoreRepository.php(105): Magento\Framework\App\Config->get('scopes', 'stores/1', Array)
#19 /var/www/magento2/vendor/magento/module-store/Model/StoreRepository.php(124): Magento\Store\Model\StoreRepository->getById('1')
#20 /var/www/magento2/vendor/magento/module-store/Model/StoreResolver.php(167): Magento\Store\Model\StoreRepository->getActiveStoreById('1')
#21 /var/www/magento2/vendor/magento/module-store/Model/StoreResolver.php(105): Magento\Store\Model\StoreResolver->getDefaultStoreById('1')
#22 /var/www/magento2/vendor/magento/module-store/Model/StoreManager.php(154): Magento\Store\Model\StoreResolver->getCurrentStoreId()
#23 /var/www/magento2/var/generation/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL)
#24 /var/www/magento2/vendor/magento/module-store/Model/Resolver/Store.php(29): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL)
#25 /var/www/magento2/vendor/magento/framework/App/Config/ScopeCodeResolver.php(49): Magento\Store\Model\Resolver\Store->getScope(NULL)
#26 /var/www/magento2/vendor/magento/framework/App/Config.php(79): Magento\Framework\App\Config\ScopeCodeResolver->resolve('stores', NULL)
#27 /var/www/magento2/vendor/magento/framework/View/DesignExceptions.php(63): Magento\Framework\App\Config->getValue('design/theme/ua...', 'stores')
#28 /var/www/magento2/vendor/magento/module-page-cache/Model/App/CacheIdentifierPlugin.php(43): Magento\Framework\View\DesignExceptions->getThemeByRequest(Object(Magento\Framework\App\Request\Http))
#29 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(152): Magento\PageCache\Model\App\CacheIdentifierPlugin->afterGetValue(Object(Magento\Framework\App\PageCache\Identifier\Interceptor), '1846527cee9540c...')
#30 /var/www/magento2/var/generation/Magento/Framework/App/PageCache/Identifier/Interceptor.php(26): Magento\Framework\App\PageCache\Identifier\Interceptor->___callPlugins('getValue', Array, Array)
#31 /var/www/magento2/vendor/magento/framework/App/PageCache/Kernel.php(60): Magento\Framework\App\PageCache\Identifier\Interceptor->getValue()
#32 /var/www/magento2/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\PageCache\Kernel->load()
#33 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 /var/www/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#35 /var/www/magento2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#36 /var/www/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#37 /var/www/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#38 {main}

Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.store' doesn't exist
#0 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/magento2/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#3 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `store`....', Array)
#5 /var/www/magento2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(465): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `store`....', Array)
#6 /var/www/magento2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(520): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `store`....', Array)
#7 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(756): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#8 /var/www/magento2/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(342): Zend_Db_Adapter_Abstract->fetchRow(Object(Magento\Framework\DB\Select))
#9 /var/www/magento2/var/generation/Magento/Store/Model/ResourceModel/Store/Interceptor.php(102): Magento\Framework\Model\ResourceModel\Db\AbstractDb->load(Object(Magento\Store\Model\Store\Interceptor), '1', 'store_id')
#10 /var/www/magento2/vendor/magento/framework/Model/AbstractModel.php(531): Magento\Store\Model\ResourceModel\Store\Interceptor->load(Object(Magento\Store\Model\Store\Interceptor), '1', NULL)
#11 /var/www/magento2/vendor/magento/module-store/Model/Store.php(488): Magento\Framework\Model\AbstractModel->load('1', NULL)
#12 /var/www/magento2/var/generation/Magento/Store/Model/Store/Interceptor.php(24): Magento\Store\Model\Store->load('1', NULL)
#13 /var/www/magento2/vendor/magento/module-store/App/Config/Source/RuntimeConfigSource.php(181): Magento\Store\Model\Store\Interceptor->load('1')
#14 /var/www/magento2/vendor/magento/module-store/App/Config/Source/RuntimeConfigSource.php(112): Magento\Store\App\Config\Source\RuntimeConfigSource->getStoresData('1')
#15 /var/www/magento2/vendor/magento/framework/App/Config/ConfigSourceAggregated.php(40): Magento\Store\App\Config\Source\RuntimeConfigSource->get('stores/1')
#16 /var/www/magento2/var/generation/Magento/Framework/App/Config/ConfigSourceAggregated/Proxy.php(95): Magento\Framework\App\Config\ConfigSourceAggregated->get('stores/1')
#17 /var/www/magento2/vendor/magento/module-store/App/Config/Type/Scopes.php(50): Magento\Framework\App\Config\ConfigSourceAggregated\Proxy->get('stores/1')
#18 /var/www/magento2/vendor/magento/framework/App/Config.php(139): Magento\Store\App\Config\Type\Scopes->get('stores/1')
#19 /var/www/magento2/vendor/magento/module-store/Model/StoreRepository.php(105): Magento\Framework\App\Config->get('scopes', 'stores/1', Array)
#20 /var/www/magento2/vendor/magento/module-store/Model/StoreRepository.php(124): Magento\Store\Model\StoreRepository->getById('1')
#21 /var/www/magento2/vendor/magento/module-store/Model/StoreResolver.php(167): Magento\Store\Model\StoreRepository->getActiveStoreById('1')
#22 /var/www/magento2/vendor/magento/module-store/Model/StoreResolver.php(105): Magento\Store\Model\StoreResolver->getDefaultStoreById('1')
#23 /var/www/magento2/vendor/magento/module-store/Model/StoreManager.php(154): Magento\Store\Model\StoreResolver->getCurrentStoreId()
#24 /var/www/magento2/var/generation/Magento/Store/Model/StoreManagerInterface/Proxy.php(119): Magento\Store\Model\StoreManager->getStore(NULL)
#25 /var/www/magento2/vendor/magento/module-store/Model/Resolver/Store.php(29): Magento\Store\Model\StoreManagerInterface\Proxy->getStore(NULL)
#26 /var/www/magento2/vendor/magento/framework/App/Config/ScopeCodeResolver.php(49): Magento\Store\Model\Resolver\Store->getScope(NULL)
#27 /var/www/magento2/vendor/magento/framework/App/Config.php(79): Magento\Framework\App\Config\ScopeCodeResolver->resolve('stores', NULL)
#28 /var/www/magento2/vendor/magento/framework/View/DesignExceptions.php(63): Magento\Framework\App\Config->getValue('design/theme/ua...', 'stores')
#29 /var/www/magento2/vendor/magento/module-page-cache/Model/App/CacheIdentifierPlugin.php(43): Magento\Framework\View\DesignExceptions->getThemeByRequest(Object(Magento\Framework\App\Request\Http))
#30 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(152): Magento\PageCache\Model\App\CacheIdentifierPlugin->afterGetValue(Object(Magento\Framework\App\PageCache\Identifier\Interceptor), '1846527cee9540c...')
#31 /var/www/magento2/var/generation/Magento/Framework/App/PageCache/Identifier/Interceptor.php(26): Magento\Framework\App\PageCache\Identifier\Interceptor->___callPlugins('getValue', Array, Array)
#32 /var/www/magento2/vendor/magento/framework/App/PageCache/Kernel.php(60): Magento\Framework\App\PageCache\Identifier\Interceptor->getValue()
#33 /var/www/magento2/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\PageCache\Kernel->load()
#34 /var/www/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /var/www/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /var/www/magento2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /var/www/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#38 /var/www/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#39 {main}

**Comment by MmtBkn** [comment]
Just realized #86
