### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 9

### ISSUE THREAD

**Issue by vovan1983** [magento/magento2devbox-web#60]
System:
Windows 7 SP1. Russian locale. Docker Toolbox. Docker -v: Docker version 1.12.6 build 78d1802.
Docker Terminal: ./m2devbox-init.bat. After start this exception:
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 62, in main
  File "compose\cli\main.py", line 111, in perform_command
  File "compose\cli\command.py", line 35, in project_from_options
  File "compose\cli\command.py", line 102, in get_project
  File "compose\config\config.py", line 319, in load
  File "compose\config\config.py", line 409, in load_services
  File "compose\config\config.py", line 388, in build_services
  File "compose\config\config.py", line 373, in build_service
  File "compose\config\config.py", line 612, in process_service
  File "compose\config\config.py", line 856, in resolve_volume_paths
  File "compose\config\config.py", line 866, in resolve_volume_path
  File "ntpath.py", line 311, in expanduser
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 9: ordinal not in range(128)
docker-compose returned -1
What could it be? Thanks.

**Comment by xcomSteveJohnson** [comment]
Because of the Docker requirement for Hyper-V, Windows 7 is not supported for DevBox.

**Comment by vovan1983** [comment]
https://docs.docker.com/docker-for-windows/ 
it is written
>>The Hyper-V package must be enabled for Docker for Windows to work. The Docker for Windows installer will enable it for you, if needed. (This requires a reboot). If your system does not satisfy these requirements, you can install Docker Toolbox, which uses Oracle Virtual Box instead of Hyper-V.

I use docker toolbox with oracle virtual box. I can build and run any containers

**Comment by piotrekkaminski** [comment]
We have never tested or tried to be compatible with Docker Toolbox @vovan1983 . It uses different file sharing technology to my understanding. We do not currently have plans to support this technology.
