### ISSUE TITLE
I have to setup the database every time after restart computer or docker

### ISSUE THREAD

**Issue by juchunwei** [magento/magento2devbox-web#86]
Hello,  every I restart my computer or docker, I got this error message, and have to setup the database again and all the products. this is crazy! any idea?

PDOException:SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.core_config_data' doesn't exist in /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228 Stack trace: #0 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array) #1 /var/www/magento2/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array) #2 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array) #3 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array) #4 /var/www/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array) #5  .....

**Comment by yaroslavGoncharuk** [comment]
@juchunwei thanks for reporting this issue.

In addition, identify, please:
Your OS type and version 
Docker version and additional settings
Magento Edition and Version
Project Source (New Installation or Use Existing Local Installation)

**Comment by juchunwei** [comment]
@yaroslavGoncharuk , my OS: Windows 10 Prod 64 bit. 
Docker CE: 17.03.0-ce-win1 (10296)
Magento: CE 2.1.5
Project Source: New Installation
thanks.

**Comment by kamleshyaduwanshi** [comment]
Experiencing similar issue, and having same windows configuration as @yaroslavGoncharuk.
Please help on this. thanks in advance.

**Comment by adragus-inviqa** [comment]
Is it just me, or there's no volume when creating this container? This means that the container is always ephemeral (thus nothing is persisted). 

For the DB to be persisted , you'd need something like `VOLUME /var/lib/mysql` in the `Dockerfile`, amirite?

**Comment by RedAtRareCandy** [comment]
Also having this issue.

OS: Windows 10 Prod 64-bit
Docker CE: 17.03.1-ce-win5 (10743)
Magento: CE 2.1.6
Project Source: New Installation

 Two months without some kind of investigation? I should've stuck with Vagrant, it seems. I was a fool to think a Beta would work well enough, I just figured it was Magento-endorsed, I should get behind it...

@adragus-inviqa 
The docker-compose.yml does have that line?

        volumes:
          - "./shared/db:/var/lib/mysql"
          - "./shared/var/logs/mysql:/var/log/mysql"

**Comment by RedAtRareCandy** [comment]
Hi all,

I believe I know how to resolve this in the interim, until Magento put in a better solution.

I believe that once Docker is closed and relaunched, it doesn't restart the db container. If you do "docker-compose restart db" and refresh the Magento page or Admin, it'll no longer show the "base table or view not found" error and will show correctly.

Add the above also to original issue ticket: https://github.com/magento/magento2devbox-web/issues/39

**Comment by iflow** [comment]
Same problem here. After restarting VirtualBox the Magento2 database was destroyed! No tables left...
So I tried to re-init the devbox, but this leads to this error:
```
PS D:\Dev\m2devbox> .\m2devbox-reset.bat
Install Magento
unable to find user magento2: no matching entries in passwd file
```

**Comment by johnark88** [comment]
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento2.core_config_data' doesn't exist in 

Same issue.

MacOS Sierra 10.12.5

Docker -- 
Version 17.06.0-ce-mac18 (18433)
Channel: stable
d9b66511e0

Magento 2.1.7 ce

**Comment by arumcomputer** [comment]
same issue Windows 10 Pro 64 bit

**Comment by Echron** [comment]
This is because when the MySql server is started the shared drive with database files is not yet ready. So MySql can't read them and creates an empty database. Simply restarting the database after the shared storage is ready (it's a matter of seconds) will work.

The solution above works but i think there should be something more "elegant"
